packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  next: ^16.2.6
  "@trpc/server": ^11.7.2
  "@trpc/client": ^11.7.2
  better-auth: 1.6.16
  drizzle-orm: ^0.45.2
  "@types/pg": ^8.16.0
